package com.example.backend.service;

import com.example.backend.dto.ai.*;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.http.MediaType;
import org.springframework.http.client.MultipartBodyBuilder;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.reactive.function.BodyInserters;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.reactive.function.client.WebClientResponseException;
import reactor.core.publisher.Flux;

import java.io.IOException;
import java.util.List;
import java.util.Map;

/**
 * HTTP client for communicating with the AI Server (FastAPI RAG Backend).
 *
 * All RAG-related operations (query, ingestion, Law management) go through this service.
 * The AI Server runs independently on a separate port and handles:
 * - Document ingestion (Law/LawChunk schema with LLM-generated metadata)
 * - RAG queries (hybrid search, reranking, LLM generation)
 * - Reflection RAG (iterative self-correction)
 * - SSE streaming responses
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class AiServerClient {

    private final WebClient aiServerWebClient;

    // ═══════════════════════════════════════════════════════════
    // QUERY ENDPOINTS
    // ═══════════════════════════════════════════════════════════

    /**
     * Execute a standard RAG query (synchronous).
     * Pipeline: Query Rewrite → Hybrid Search → Rerank → Context Build → LLM Generate.
     *
     * @param request the RAG query parameters
     * @return RAG response with answer and citations
     */
    public RAGResponse query(RAGQueryRequest request) {
        log.info("Sending RAG query to AI Server: {}", request.getQuery());

        try {
            RAGResponse response = aiServerWebClient.post()
                    .uri("/api/v1/query/")
                    .bodyValue(request)
                    .retrieve()
                    .bodyToMono(RAGResponse.class)
                    .block();

            log.info("RAG query completed. Citations: {}", 
                    response != null && response.getCitations() != null ? response.getCitations().size() : 0);
            return response;

        } catch (WebClientResponseException e) {
            log.error("AI Server returned error for query: {} - {}", e.getStatusCode(), e.getResponseBodyAsString());
            throw new RuntimeException("AI Server query failed: " + e.getMessage(), e);
        } catch (Exception e) {
            log.error("Failed to connect to AI Server for query: {}", e.getMessage());
            throw new RuntimeException("AI Server is unavailable. Please try again later.", e);
        }
    }

    /**
     * Execute a RAG query with SSE streaming response.
     * Returns tokens in real-time as they are generated by the LLM.
     *
     * @param request the RAG query parameters
     * @return Flux of SSE events (token strings)
     */
    public Flux<String> queryStream(RAGQueryRequest request) {
        log.info("Sending streaming RAG query to AI Server: {}", request.getQuery());

        return aiServerWebClient.post()
                .uri("/api/v1/query/stream")
                .bodyValue(request)
                .retrieve()
                .bodyToFlux(String.class)
                .doOnError(e -> log.error("Streaming query error: {}", e.getMessage()));
    }



    // ═══════════════════════════════════════════════════════════
    // DOCUMENT / CHUNK MANAGEMENT
    // ═══════════════════════════════════════════════════════════

    public void deleteDocument(String documentId, String collectionName) {
        log.info("Deleting document from AI Server: {} in collection '{}'", documentId, collectionName);

        try {
            aiServerWebClient.method(org.springframework.http.HttpMethod.DELETE)
                    .uri("/api/v1/ingestion/document")
                    .bodyValue(Map.of(
                            "document_id", documentId,
                            "collection_name", collectionName
                    ))
                    .retrieve()
                    .bodyToMono(Void.class)
                    .block();

            log.info("Document deleted successfully: {}", documentId);

        } catch (WebClientResponseException e) {
            log.error("AI Server returned error for delete: {} - {}", e.getStatusCode(), e.getResponseBodyAsString());
            throw new RuntimeException("Document deletion failed: " + e.getMessage(), e);
        }
    }

    // ═══════════════════════════════════════════════════════════
    // LAW MANAGEMENT ENDPOINTS (Weaviate source of truth)
    // ═══════════════════════════════════════════════════════════

    /**
     * List all Law objects from Weaviate via AI Server.
     *
     * @return list of LawInfo (law_uuid, title, description, chunk_count, source_files)
     */
    @SuppressWarnings("unchecked")
    public List<LawInfo> listLaws() {
        log.debug("Listing laws from AI Server (Weaviate)");
        try {
            Map<String, Object> response = aiServerWebClient.get()
                    .uri("/api/v1/ingestion/laws")
                    .retrieve()
                    .bodyToMono(new ParameterizedTypeReference<Map<String, Object>>() {})
                    .block();

            if (response == null || !response.containsKey("laws")) {
                return List.of();
            }

            List<Map<String, Object>> rawList =
                    (List<Map<String, Object>>) response.get("laws");

            return rawList.stream().map(m -> LawInfo.builder()
                    .lawUuid((String) m.get("law_uuid"))
                    .title((String) m.getOrDefault("title", ""))
                    .description((String) m.getOrDefault("description", ""))
                    .keywords((List<String>) m.getOrDefault("keywords", List.of()))
                    .sourceFiles((List<String>) m.getOrDefault("source_files", List.of()))
                    .chunkCount(m.get("chunk_count") != null
                            ? ((Number) m.get("chunk_count")).intValue() : 0)
                    .build()
            ).toList();

        } catch (Exception e) {
            log.error("Failed to list laws from AI Server: {}", e.getMessage());
            return List.of();
        }
    }

    /**
     * Create a new Law object by uploading 1 or more files.
     * AI Server: extract → LLM generate title/description → chunk → embed → store.
     *
     * @param files list of PDF/document files (first creates Law, rest are appended)
     * @return LawCreateResponse with generated law_uuid and per-file results
     */
    public LawCreateResponse createLaw(List<MultipartFile> files) throws IOException {
        log.info("Creating new Law from {} file(s)", files.size());

        MultipartBodyBuilder builder = new MultipartBodyBuilder();
        for (MultipartFile file : files) {
            builder.part("files", new ByteArrayResource(file.getBytes()) {
                @Override
                public String getFilename() { return file.getOriginalFilename(); }
            }).contentType(MediaType.APPLICATION_OCTET_STREAM);
        }

        try {
            return aiServerWebClient.post()
                    .uri("/api/v1/ingestion/laws")
                    .contentType(MediaType.MULTIPART_FORM_DATA)
                    .body(BodyInserters.fromMultipartData(builder.build()))
                    .retrieve()
                    .bodyToMono(LawCreateResponse.class)
                    .block();

        } catch (WebClientResponseException e) {
            log.error("AI Server error creating Law: {} - {}", e.getStatusCode(), e.getResponseBodyAsString());
            throw new RuntimeException("Law creation failed: " + e.getMessage(), e);
        }
    }

    /**
     * Add 1 or more files to an existing Law (incremental ingestion).
     * AI Server: extract → LLM update description → chunk → embed → store.
     *
     * @param lawUuid Weaviate UUID of the target Law
     * @param files   list of additional PDF/document files
     * @return FilesAddToLawResponse with chunks_added per file
     */
    public FilesAddToLawResponse addFilesToLaw(String lawUuid, List<MultipartFile> files) throws IOException {
        log.info("Adding {} file(s) to Law uuid={}", files.size(), lawUuid);

        MultipartBodyBuilder builder = new MultipartBodyBuilder();
        for (MultipartFile file : files) {
            builder.part("files", new ByteArrayResource(file.getBytes()) {
                @Override
                public String getFilename() { return file.getOriginalFilename(); }
            }).contentType(MediaType.APPLICATION_OCTET_STREAM);
        }

        try {
            return aiServerWebClient.post()
                    .uri("/api/v1/ingestion/laws/" + lawUuid + "/files")
                    .contentType(MediaType.MULTIPART_FORM_DATA)
                    .body(BodyInserters.fromMultipartData(builder.build()))
                    .retrieve()
                    .bodyToMono(FilesAddToLawResponse.class)
                    .block();

        } catch (WebClientResponseException e) {
            log.error("AI Server error adding files to Law {}: {} - {}",
                    lawUuid, e.getStatusCode(), e.getResponseBodyAsString());
            throw new RuntimeException("Add files to Law failed: " + e.getMessage(), e);
        }
    }

    // ═══════════════════════════════════════════════════════════
    // LAW DELETION (cascade)
    // ═══════════════════════════════════════════════════════════

    /**
     * Cascade-delete a Law and ALL its associated LawChunk objects from Weaviate.
     *
     * AI Server execution order:
     * 1. Batch-delete all LawChunk objects where law_uuid matches (filter delete).
     * 2. Delete the Law object itself by UUID.
     *
     * @param lawUuid Weaviate UUID of the Law to delete
     * @return DeleteLawResponse with chunks_deleted count and law_deleted flag
     */
    @SuppressWarnings("unchecked")
    public DeleteLawResponse deleteLaw(String lawUuid) {
        log.info("Cascade-deleting Law uuid={} from AI Server", lawUuid);

        try {
            Map<String, Object> raw = aiServerWebClient
                    .delete()
                    .uri("/api/v1/ingestion/laws/" + lawUuid)
                    .retrieve()
                    .bodyToMono(Map.class)
                    .block();

            if (raw == null) {
                return DeleteLawResponse.builder()
                        .lawUuid(lawUuid)
                        .chunksDeleted(0)
                        .lawDeleted(false)
                        .status("error")
                        .build();
            }

            return DeleteLawResponse.builder()
                    .lawUuid(lawUuid)
                    .chunksDeleted(raw.get("chunks_deleted") != null
                            ? ((Number) raw.get("chunks_deleted")).intValue() : 0)
                    .lawDeleted(Boolean.TRUE.equals(raw.get("law_deleted")))
                    .status((String) raw.getOrDefault("status", "deleted"))
                    .build();

        } catch (WebClientResponseException e) {
            log.error("AI Server error deleting Law {}: {} - {}",
                    lawUuid, e.getStatusCode(), e.getResponseBodyAsString());
            throw new RuntimeException("Law deletion failed: " + e.getMessage(), e);
        }
    }

    // ═══════════════════════════════════════════════════════════
    // HEALTH CHECK
    // ═══════════════════════════════════════════════════════════

    /**
     * Check if the AI Server is healthy and responsive.
     *
     * @return true if AI Server is reachable
     */
    public boolean isHealthy() {
        try {
            Map<String, Object> response = aiServerWebClient.get()
                    .uri("/health")
                    .retrieve()
                    .bodyToMono(Map.class)
                    .block();

            return response != null && "healthy".equals(response.get("status"));
        } catch (Exception e) {
            log.warn("AI Server health check failed: {}", e.getMessage());
            return false;
        }
    }
}
