"""Collection registry models — tracks collections with contextual metadata."""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field


class CollectionInfo(BaseModel):
    """Metadata for a vector collection with contextual header.

    Each collection represents one legal document/law category.
    The title and description are generated by LLM from the document's
    opening content (Contextual Chunk Headers technique).
    """

    collection_name: str
    title: str                          # LLM-generated title
    description: str                    # LLM-generated summary
    keywords: list[str] = Field(default_factory=list)  # Key terms for matching
    title_embedding: list[float] = Field(default_factory=list)  # Embedded title+description
    document_count: int = 0
    chunk_count: int = 0
    created_at: datetime = Field(default_factory=datetime.utcnow)
    source_files: list[str] = Field(default_factory=list)


class CollectionRegistry(BaseModel):
    """Registry of all collections with their contextual metadata.

    Used by the Collection Router to match queries to the right collection.
    """

    collections: dict[str, CollectionInfo] = Field(default_factory=dict)

    def add(self, info: CollectionInfo) -> None:
        """Register a collection."""
        self.collections[info.collection_name] = info

    def remove(self, collection_name: str) -> None:
        """Remove a collection from registry."""
        self.collections.pop(collection_name, None)

    def get(self, collection_name: str) -> CollectionInfo | None:
        """Get collection info by name."""
        return self.collections.get(collection_name)

    def list_all(self) -> list[CollectionInfo]:
        """List all registered collections."""
        return list(self.collections.values())
